# permissions for end users to edit ticketstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ticketstore-editor-role
rules:
- apiGroups:
  - charts.my.domain
  resources:
  - ticketstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.my.domain
  resources:
  - ticketstores/status
  verbs:
  - get
