# permissions for end users to view ticketstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ticketstore-viewer-role
rules:
- apiGroups:
  - charts.my.domain
  resources:
  - ticketstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.my.domain
  resources:
  - ticketstores/status
  verbs:
  - get
