{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ticket-store.serviceAccountName" . }}
  labels:
{{ include "ticket-store.labels" . | nindent 4 }}
{{- end -}}
