{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "landmark.serviceAccountName" . }}
  labels:
{{ include "landmark.labels" . | nindent 4 }}
{{- end -}}
