apiVersion: v1
kind: Service
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ include "landmark.fullname" . }}
  labels:
    {{- include "landmark.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }}
      nodePort: {{ .Values.service.ports.nodePort}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "landmark.selectorLabels" . | nindent 4 }}
